apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-db
  name: mongo-db
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-db
    spec:
      containers:
      - args:
        - --bind_ip_all
        - --smallfiles
        image: mongo:4.0.5
        name: mongo-db
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: mongo-db-claim0
      hostname: mongo-db
      restartPolicy: Always
      volumes:
      - name: mongo-db-claim0
        persistentVolumeClaim:
          claimName: mongo-db-claim0
status: {}
